### PR TITLE
Added 5 new Kerberos hash types

### PR DESCRIPTION
**Pull request by amadejpapez**
- added "Kerberos 5 AS-REP etype 23",
- added "Kerberos 5 TGS-REP etype 17 (AES128-CTS-HMAC-SHA1-96)",
- added "Kerberos 5 TGS-REP etype 18 (AES256-CTS-HMAC-SHA1-96)",
- added "Kerberos 5, etype 18, Pre-Auth",
- added "Kerberos 5, etype 17, Pre-Auth" twice as hashcat and john support it differently,
- changed regex of "Kerberos 5 AS-REQ Pre-Auth" as it was too broad and it matched to some of the new ones,
- fixed individual Kerberos tests

Fixed it so I hope it all works now :)

### CODE REVIEW

**Comment by bee-san** [comment]
Hey, your tests don't run. Please run `pytest` and ensure all tests run :) 
image

**Comment by amadejpapez** [comment]
Looks like a messed up when I copied the tests yeah... Could you try once again as I fixed it. :)

**Review by bee-san — APPROVED** [review]

**Comment by bee-san** [comment]
Thanks! All tests passed :) <3

**Comment by bee-san** [comment]
This fixes #59

**Comment by amadejpapez** [comment]
> Thanks! All tests passed :) <3 

Glad to help! Will also try to add some other hash types as I saw there is a lot more to add :D

**Review by bburky — COMMENTED** [review]
Sorry for if I was unclear at first, all of the 17 and 18 hashes need to be split into "with salt" and without.

Arguably this whole thing is a hashcat bug, maybe just report it to them?

**Pull request merged**
