### PR TITLE
Wrong url on the readme

### PR DESCRIPTION
**Pull request by phosphorus0xF**
The url on "website" was mistyped, i fixed it.

### CODE REVIEW

**Comment by bee-san** [comment]
Nice catch!! :D

**Comment by phosphorus0xF** [comment]
no worries :)

**Comment by bee-san** [comment]
Hey @phosphorus0xF  , just some boring legal stuff. We were previously under NOLICENSE, now we're under GNU General Public License v3.0 which is in line with HashID and Hash-Identifier.

This is just to ask if you mind at all? This is still a 100% open source project, just we've finally gotten a license :D

https://github.com/HashPals/Name-That-Hash/blob/main/LICENSE

**Comment by phosphorus0xF** [comment]
@bee-san all good, no problem :)

**Pull request merged**
